### ISSUE TITLE
[Question] appearance to other clients?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [SarahIsWeird/WeirdChat#1]
So I was just wondering does the emoji appear as text or as a unique character in chat to other people. 

Basically similarly to how Symbol chat is, where in their description they say that other people without the mod would still see it. 

Obviously it won't appear as a colored emoji but, like maybe something similar?

**Comment by SarahIsWeird** [comment]
Sorry for the late reply, for some reason GitHub didn't notify me of the issue. The emoji will appear to users without the mod as the shortcode, so if you'd see `Some text 😄`, they'd see `Some text :smile:`.

**Comment by Aces-and-Jacks** [comment]
Ah ok. Thanks for clarifying
