### ISSUE TITLE
No Suggestions Initially in Multiplayer

### ISSUE THREAD

**Issue by lewxdev** [SarahIsWeird/WeirdChat#4]
Not sure if this is an issue with [WeirdChat](https://github.com/SarahIsWeird/WeirdChat) or [MoreChatSuggestions](https://github.com/SarahIsWeird/MoreChatSuggestions), but in my case I seem to have to open a single-player world in order for the suggestions to show up. I'm not sure how the mod works under-the-hood, but whenever I open a multiplayer world on initial launch of the game, suggestions and shortcode replacement don't work.

**Comment by SarahIsWeird** [comment]
Fixed in [v1.0.2](https://modrinth.com/mod/weirdchat/version/v1.0.2)!
